name: dataviz
channels:
  - conda-forge
  - defaults
dependencies:
  - astroid=2.3.2
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.10.16
  - certifi=2019.9.11
  - colorama=0.4.1
  - cycler=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - icu=58.2
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipympl=0.3.3
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - jedi=0.15.1
  - jinja2=2.10.3
  - jpeg=9b
  - json5=0.8.5
  - jsonschema=3.1.1
  - jupyter_client=5.3.4
  - jupyter_core=4.6.0
  - jupyterlab=1.1.4
  - jupyterlab_server=1.0.6
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.2
  - libpng=1.6.37
  - libsodium=1.0.16
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - more-itertools=7.2.0
  - nb_conda_kernels=2.2.2
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - notebook=6.0.1
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openssl=1.1.1d
  - pandas=0.25.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pickleshare=0.7.5
  - pip=19.3.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - pygments=2.4.2
  - pylint=2.4.3
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - python=3.7.5
  - python-dateutil=2.8.0
  - pytz=2019.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - send2trash=1.5.0
  - setuptools=41.6.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.30.1
  - terminado=0.8.2
  - testpath=0.4.2
  - tornado=6.0.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - awscli=
    - botocore=
    - docutils=
    - jmespath=
    - pyasn1=
    - python-dotenv=
    - rsa=
    - s3transfer=
    - urllib3=
